# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run

name: CI with install

on:
  pull_request:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openmc-data-storage/miniconda3_4.9.2_endfb-7.1_nndc_tendl_2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          conda install -c conda-forge openmc
          python setup.py install

      - name: install packages for tests
        run: |
          pip install -r requirements-test.txt

      - name: Run test_utils
        run: |
          python tests/create_statepoint_file_for_testing.py --batches 2 --particles 100
          python tests/create_statepoint_file_for_testing.py --batches 1 --particles 100
          pytest tests -v --cov=openmc_tally_unit_converter --cov-append --cov-report term --cov-report xml

      - name: Run examples
        run: |
          cd examples
          python create_statepoint_file_for_testing.py --batches 2 --particles 100
          python processing_2d_mesh_effective_dose_tally.py
          python processing_cell_damage-energy_tally.py
          python processing_cell_effective_dose_tally.py
          python processing_cell_flux_tally.py
          python processing_cell_heating_tally.py
          python processing_cell_spectra_tally.py
          python processing_mutliple_cell_spectra_tally.py
          python processing_2d_mesh_heating_tally.py
          python processing_3d_mesh_heating_tally.py

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
